const countriesArray = [
  { Country: "United Kingdom", Total: 22 },
  { Country: "Canada", Total: 19 },
  { Country: "Germany", Total: 24 },
  { Country: "Australia", Total: 13 },
  { Country: "Russian Federation", Total: 17 },
  { Country: "Brazil", Total: 15 },
  { Country: "Sweden", Total: 14 },
  { Country: "Finland", Total: 12 },
  { Country: "Czechia", Total: 26 },
  { Country: "Italy", Total: 28 },
  { Country: "Korea, Republic of", Total: 140 },
  { Country: "Poland", Total: 30 },
  { Country: "Saudi Arabia", Total: 10 },
  { Country: "France", Total: 16 },
  { Country: "Thailand", Total: 18 },
  { Country: "Philippines", Total: 20 },
  { Country: "Hungary", Total: 27 },
  { Country: "Netherlands", Total: 29 },
  { Country: "Indonesia", Total: 11 },
  { Country: "Romania", Total: 23 },
  { Country: "India", Total: 25 },
  { Country: "Viet Nam", Total: 14 },
  { Country: "Slovakia", Total: 17 },
  { Country: "Japan", Total: 15 },
  { Country: "United Arab Emirates", Total: 13 },
  { Country: "Taiwan, Province of China", Total: 18 },
  { Country: "Ukraine", Total: 19 },
  { Country: "Norway", Total: 20 },
  { Country: "Malaysia", Total: 21 },
  { Country: "Ireland", Total: 22 },
  { Country: "Croatia", Total: 23 },
  { Country: "Türkiye", Total: 24 },
  { Country: "New Zealand", Total: 25 },
  { Country: "Serbia", Total: 26 },
  { Country: "Bulgaria", Total: 27 },
  { Country: "Hong Kong", Total: 28 },
  { Country: "Austria", Total: 29 },
  { Country: "Denmark", Total: 30 },
  { Country: "Switzerland", Total: 10 },
  { Country: "Spain", Total: 120 },
  { Country: "Mexico", Total: 12 },
  { Country: "Portugal", Total: 13 },
  { Country: "Singapore", Total: 14 },
  { Country: "Belgium", Total: 15 },
  { Country: "Israel", Total: 16 },
  { Country: "Argentina", Total: 17 },
  { Country: "Estonia", Total: 18 },
  { Country: "South Africa", Total: 19 },
  { Country: "Bosnia and Herzegovina", Total: 20 },
  { Country: "Iraq", Total: 21 },
  { Country: "Egypt", Total: 22 },
  { Country: "Lithuania", Total: 23 },
  { Country: "Greece", Total: 24 },
  { Country: "Kuwait", Total: 25 },
  { Country: "Kazakhstan", Total: 26 },
  { Country: "Algeria", Total: 27 },
  { Country: "Latvia", Total: 28 },
  { Country: "Colombia", Total: 29 },
  { Country: "Chile", Total: 30 },
  { Country: "Belarus", Total: 10 },
  { Country: "Qatar", Total: 11 },
  { Country: "Cambodia", Total: 12 },
  { Country: "Slovenia", Total: 13 },
  { Country: "Jordan", Total: 14 },
];
